#!/usr/bin/env perl

use strict;
use File::Find;
use File::Path;

use constant sparrow_list => 'sparrow.list';

unless (@ARGV) {

    usage();
    exit;
}


sub show_plugins {

    my $list = read_plugin_list();

    for my $p (@{$list}){
        print "$p->{name} | $p->{url}\n";
    }
}

sub read_plugin_list {

    my @list;
    open F, sparrow_list or die $!;
    while ( my $i = <F> ){
        chomp $i;
        next unless $i=~/\S+/;
        my @foo = split /\s+/, $i;
        push @list, { name => $foo[0], url => $foo[1] } ;
    }
    close F;

    [@list];

}

sub show_local_plugins {

    mkpath('plugins/');
    for my $p (<plugins/*>){
        print "$p\n";
    }
}

sub install_plugin {

    my $pid = shift;
    
}



sub usage {

    print "usage: sparrow project|plg action args\n";
    print "where action: create|list|install|update|add_site|check_site|swat_setup. and args depend on action\n";
    print "examples:\n";
    print "\tsparrow plg list\n";
    print "\tsparrow plg list --local\n";
    print "\tsparrow plg install nginx\n";
    print "\tsparrow plg update tomcat\n";
    print "\tsparrow project foo create\n";
    print "\tsparrow project foo add_plg nginx\n";
    print "\tsparrow project foo add_plg tomcat\n";
    print "\tsparrow project foo add_plg tomcat\n";
    print "\tsparrow project foo add_site nginx_proxy 127.0.0.1\n";
    print "\tsparrow project foo add_site tomcat_app 127.0.0.1:8080\n";
    print "\tsparrow project foo check_site nginx_proxy nginx\n";
    print "\tsparrow project foo check_site tomcat_app nginx\n";
    print "\tsparrow project foo swat_setup nginx_proxy /path/to/swat.ini";
    print "\n";
    print "follow doc site - https://github.com/melezhik/sparrow to get more\n";

}
