#!/usr/bin/env perl

use strict;
use File::Path;
use File::Basename;
use Carp;

use constant sparrow_list => 'sparrow.list';

unless (@ARGV) {

    usage();
    exit;
}



my $object = shift @ARGV;


if ($object eq  'plg'){

    my $action = shift @ARGV;

    if ( $action eq 'list') {

        my $options = join ' ', @ARGV;

        if ($options =~ /--local/){
            show_local_plugins();
        } else {
            show_plugins();
        }

    } elsif ( $action eq 'install'){

        install_plugin( shift @ARGV );        

    }elsif( $action  eq 'update'){

        update_plugin( shift @ARGV );        
    }
}

## functions ###

sub read_plugin_list {

    my @list;
    my %list;

    my $mode = shift || 'as_array';

    open F, sparrow_list or confess $!;

    while ( my $i = <F> ){
        chomp $i;
        next unless $i=~/\S+/;
        my @foo = split /\s+/, $i;
        push @list, { name => $foo[0], url => $foo[1] } ;
        $list{$foo[0]} = { name => $foo[0], url => $foo[1] };
    }
    close F;

    my $retval;

    if ($mode eq 'as_hash'){
        $retval = \%list;
    }else{
        $retval = \@list;
    }

    return $retval;

}

sub show_plugins {

    my $list = read_plugin_list();

    print "available swat plugins:\n\n";

    for my $p (@{$list}){
        print "$p->{name} | $p->{url}\n";
    }
}

sub show_local_plugins {

    mkpath('plugins/');

    print "locally installed swat plugins:\n\n";

    for my $p (<plugins/*>){
        next if $p eq 'plugins/*';
        print basename($p),"\n";
    }
}

sub install_plugin {

    my $pid = shift;

    my $list = read_plugin_list('as_hash');


    if ($list->{$pid}){
        if (-d "plugins/$pid"){
            print "plugin $pid already exist!\n";
            print "you should remove plugins/$pid manualy and run `sparrow install $pid` to reinstall it\n";
            exit(1) 
        }
        print "installing plugin $pid ...\n";
        execute_shell_command("git clone $list->{$pid}->{url} plugins/$pid");
    }else{
        confess "can't find plugin $pid at sparrow list file\n";
    }
        
}

sub update_plugin {

    my $pid = shift;

    my $list = read_plugin_list('as_hash');

    if ($list->{$pid}){
        print "updating plugin $pid ...\n";
        execute_shell_command("cd plugins/$pid && git pull");
    }else{
        confess "can't find plugin $pid at sparrow list file\n";
    }
        
}



sub usage {

    print "usage: sparrow project|plg action args\n";
    print "where action: create|list|install|update|add_site|check_site|swat_setup. and args depend on action\n";
    print "examples:\n";
    print "\tsparrow plg list\n";
    print "\tsparrow plg list --local\n";
    print "\tsparrow plg install nginx\n";
    print "\tsparrow plg update tomcat\n";
    print "\tsparrow project foo create\n";
    print "\tsparrow project foo add_plg nginx\n";
    print "\tsparrow project foo add_plg tomcat\n";
    print "\tsparrow project foo add_plg tomcat\n";
    print "\tsparrow project foo add_site nginx_proxy 127.0.0.1\n";
    print "\tsparrow project foo add_site tomcat_app 127.0.0.1:8080\n";
    print "\tsparrow project foo check_site nginx_proxy nginx\n";
    print "\tsparrow project foo check_site tomcat_app nginx\n";
    print "\tsparrow project foo swat_setup nginx_proxy /path/to/swat.ini";
    print "\n";
    print "follow doc site - https://github.com/melezhik/sparrow to get more\n";

}


sub execute_shell_command {

    my $cmd = shift;

    croak "failed execute: $cmd" unless system($cmd) == 0;

}

